### ISSUE TITLE
Add to CocoaPods

### ISSUE THREAD

**Issue by Stunner** [dibelogrivaya/DBChatAvatarView#1]
Would make it so much easier to use this library, thanks! http://guides.cocoapods.org/making/making-a-cocoapod.html

**Comment by dibelogrivaya** [comment]
pod "DBChatAvatarView"

**Comment by dibelogrivaya** [comment]
**Add this to your Pdfile:**
source 'git@github.com:dibelogrivaya/db-specs.git' 
pod "DBChatAvatarView"
